name: 'Windows builds'
on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - '.travis.yml'
      - '.travis/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - '.travis.yml'
      - '.travis/**'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        pg:
          - 9.6.15
          - 10.6
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 8.0
          distribution: temurin
      - name: Install PostgreSQL
        run: |
          choco install postgresql --version ${{ matrix.pg }} --params "/Password:Password12!"
      - name: Update Paths
        run: |
          $TARGET = Resolve-Path "C:\Program Files\PostgreSQL\.*\bin\" | Select -ExpandProperty Path
          echo "$TARGET"
          echo "$TARGET" >> $env:GITHUB_PATH
          echo "TARGET=$TARGET" >> $env:GITHUB_OUTPUT
      - name: Initialize PostgreSQL
        run: |
          $initdb = Resolve-Path "C:\Program Files\PostgreSQL\.*\bin\initdb" | Select -ExpandProperty Path
          $pg_ctl = Resolve-Path "C:\Program Files\PostgreSQL\.*\bin\pg_ctl" | Select -ExpandProperty Path
          mkdir ${{ runner.temp }}/pgdata
          & $initdb -D ${{ runner.temp }}/pgdata
          echo "wal_level=logical" >> ${{ runner.temp }}/pgdata/postgresql.conf
          echo "max_wal_senders=3" >> ${{ runner.temp }}/pgdata/postgresql.conf
          echo "wal_keep_segments=10" >> ${{ runner.temp }}/pgdata/postgresql.conf
          echo "wal_sender_timeout=5s" >> ${{ runner.temp }}/pgdata/postgresql.conf
          echo "max_replication_slots=10" >> ${{ runner.temp }}/pgdata/postgresql.conf
          echo "host all all 0.0.0.0/0 trust" >> ${{ runner.temp }}/pgdata/pg_hba.conf
          echo "listen_addresses = '*'" >> ${{ runner.temp }}/pgdata/postgresql.conf
          & $pg_ctl -D ${{ env.PGDATA }} -w start
      - name: Create test user and database
        run: |
          $psql = Resolve-Path "C:\Program Files\PostgreSQL\.*\bin\psql" | Select -ExpandProperty Path
          $createdb = Resolve-Path "C:\Program Files\PostgreSQL\.*\bin\createdb" | Select -ExpandProperty Path
          & $psql -U postgres -c "CREATE USER test WITH PASSWORD 'test';"
          & $psql -U postgres -c "ALTER USER test WITH CREATEDB;"
          & $createdb -U postgres test
      - name: Build and test
        run: |
          ./gradlew -P privilegedPassword=Password12! assemble test
        env:
          PGDATABASE: test
          PGHOST: localhost
          PGPORT: 5432
          PGUSER: test
          PGPASSWORD: test
