name: 'Windows builds'
on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - '.travis.yml'
      - '.travis/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - '.travis.yml'
      - '.travis/**'
env:
  JAVA_HOME: 'C:\Program Files\Java\jdk1.8.0'
  PGDATA: ${{ runner.temp }}\pgdata

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        pg:
          - 9.6.11-1
          - 10.6-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 1.8
      - name: Install PostgreSQL
        run: |
          choco install postgresql --version ${{ matrix.pg }} --params "/Password:Password12!"
      - name: Initialize PostgreSQL
        run: |
          mkdir ${{ env.PGDATA }}
          initdb -D ${{ env.PGDATA }}
          echo "wal_level=logical" >> ${{ env.PGDATA }}/postgresql.conf
          echo "max_wal_senders=3" >> ${{ env.PGDATA }}/postgresql.conf
          echo "wal_keep_segments=10" >> ${{ env.PGDATA }}/postgresql.conf
          echo "wal_sender_timeout=5s" >> ${{ env.PGDATA }}/postgresql.conf
          echo "max_replication_slots=10" >> ${{ env.PGDATA }}/postgresql.conf
          echo "host all all 0.0.0.0/0 trust" >> ${{ env.PGDATA }}/pg_hba.conf
          echo "listen_addresses = '*'" >> ${{ env.PGDATA }}/postgresql.conf
          pg_ctl -D ${{ env.PGDATA }} -w start
      - name: Create test user and database
        run: |
          psql -U postgres -c "CREATE USER test WITH PASSWORD 'test';"
          psql -U postgres -c "ALTER USER test WITH CREATEDB;"
          createdb -U postgres test
      - name: Build and test
        run: |
          ./gradlew -P privilegedPassword=Password12! assemble test
        env:
          PGDATABASE: test
          PGHOST: localhost
          PGPORT: 5432
          PGUSER: test
          PGPASSWORD: test
